/**
 * Seed THÊM 20 TIN mới (bds023–bds042) lên Firestore — giúp bộ lọc có nhiều
 * dữ liệu: đa dạng quận, giá, loại hình, và HÌNH THỨC (Cho thuê / Bán).
 *
 * Đồng thời cập nhật lại các tin cũ bds001–bds022 để bổ sung field `deal`
 * (rent/sale) vì các tin đó được seed trước khi có hình thức giao dịch.
 *
 * Yêu cầu: file `serviceAccountKey.json` đặt ở thư mục gốc.
 * Chạy: npx tsx scripts/seed-more.ts
 */
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { cert, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

import type { Listing } from '../types';

const KEY_PATH = resolve(process.cwd(), 'serviceAccountKey.json');
if (!existsSync(KEY_PATH)) {
  console.error('[!] Thiếu serviceAccountKey.json ở thư mục gốc.');
  process.exit(1);
}

initializeApp({ credential: cert(JSON.parse(readFileSync(KEY_PATH, 'utf8'))) });
const db = getFirestore();

/** Ảnh nhà ở thật (Unsplash) — dùng lại bộ ảnh đã kiểm tra HTTP 200 ở seed-rooms */
const IMG = [
  'photo-1522708323590-d24dbb6b0267',
  'photo-1560448204-e02f11c3d0e2',
  'photo-1502672260266-1c1ef2d93688',
  'photo-1493809842364-78817add7ffb',
  'photo-1484154218962-a197022b5858',
  'photo-1554995207-c18c203602cb',
  'photo-1512917774080-9991f1c4c750',
  'photo-1600585154340-be6161a56a0c',
  'photo-1600607687939-ce8a6c25118c',
  'photo-1540518614846-7eded433c457',
  'photo-1505693416388-ac5ce068fe85',
  'photo-1540932239986-30128078f3c5',
  'photo-1586023492125-27b2c045efd7',
  'photo-1616486338812-3dadae4b4ace',
  'photo-1598928506311-c55ded91a20c',
  'photo-1556912173-3bb406ef7e77',
  'photo-1556911220-bff31c812dba',
  'photo-1513694203232-719a280e022f',
  'photo-1571508601891-ca5e7a713859',
  'photo-1560185007-cde436f6a4d0',
  'photo-1560185127-6ed189bf02f4',
  'photo-1600210492486-724fe5c67fb0',
  'photo-1600566753086-00f18fb6b3ea',
  'photo-1493663284031-b7e3aefcae8e',
  'photo-1416331108676-a22ccb276e35',
  'photo-1522771739844-6a9f6d5f14af',
  'photo-1595526114035-0d45ed16cfbf',
  'photo-1560448075-bb485b067938',
  'photo-1533779283484-8ad4940aa3a8',
  'photo-1502005097973-6a7082348e28',
].map((id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=80`);

let imgIdx = 100; // lệch chỉ số ảnh so với bds001-022 cho ảnh khác nhau
function nextImages(): string[] {
  const picks = [0, 1, 2].map(() => IMG[imgIdx++ % IMG.length]);
  return picks;
}

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

type MoreSeed = Omit<Listing, 'isFavorite' | 'images'> & { images?: string[] };

const MORE: MoreSeed[] = [
  // ---------- CHO THUÊ (deal: 'rent') ----------
  {
    id: 'bds023',
    title: 'Căn hộ 2PN Quận 1 view chợ Bến Thành — nội thất cao cấp',
    price: 17_000_000,
    area: 85,
    districtId: 'q1',
    district: 'Quận 1',
    ward: 'Phường Bến Thành',
    address: '45 Lê Thánh Tôn, Quận 1',
    type: 'can_ho',
    deal: 'rent',
    bedrooms: 2,
    bathrooms: 2,
    floor: 15,
    yearBuilt: 2021,
    description:
      'Căn hộ 2 phòng ngủ 85m² tại tòa nhà hạng A ngay trung tâm Quận 1, view thẳng chợ Bến Thành. Nội thất nhập khẩu đầy đủ, ban công rộng, hồ bơi + gym cho cư dân. Gần metro Bến Thành, đi làm chuyển phát rất thuận.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Máy giặt', 'TV', 'Thang máy', 'Bảo vệ', 'Ban công'],
    contact: { name: 'Phan Hoàng Nam', phone: '0901234567' },
    showPhone: true,
    latitude: 10.7726,
    longitude: 106.6983,
    status: 'active',
    createdAt: daysAgo(1),
    rating: 4.7,
    reviewCount: 14,
    condition: 'new',
    direction: 'Nam',
    furnished: 'full',
    views: 18_200,
    contactCount: 121,
    savedCount: 305,
  },
  {
    id: 'bds024',
    title: 'Phòng trọ rộng 25m² Quận 7 — gần Crescent, sạch sẽ',
    price: 3_600_000,
    area: 25,
    districtId: 'q7',
    district: 'Quận 7',
    ward: 'Phường Tân Phong',
    address: '12 Nguyễn Văn Linh, Quận 7',
    type: 'phong_tro',
    deal: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    floor: 2,
    yearBuilt: 2021,
    description:
      'Phòng trọ 25m² mới xây, wc riêng, có cửa sổ đón sáng. Khu dân cư Phú Mỹ Hưng yên tĩnh, an ninh tốt. Cách Crescent Mall 800m, gần các công ty IT, phù hợp nhân viên văn phòng.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'WC riêng', 'Nấu ăn', 'Bảo vệ'],
    contact: { name: 'Dương Thu Trang', phone: '0912345678' },
    showPhone: true,
    latitude: 10.7307,
    longitude: 106.7174,
    status: 'active',
    createdAt: daysAgo(2),
    rating: 4.5,
    reviewCount: 8,
    condition: 'new',
    views: 6_300,
    contactCount: 42,
    savedCount: 96,
  },
  {
    id: 'bds025',
    title: 'Căn hộ studio ĐH Văn Lang — nội thất full, giá sinh viên',
    price: 4_200_000,
    area: 30,
    districtId: 'phunhuan',
    district: 'Phú Nhuận',
    ward: 'Phường 4',
    address: 'cạnh ĐH Văn Lang, Phú Nhuận',
    type: 'can_ho',
    deal: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    floor: 4,
    yearBuilt: 2022,
    description:
      'Studio 30m² nội thất đầy đủ cách ĐH Văn Lang vài bước chân. Giường, bàn học, tủ, máy lạnh, tủ lạnh, bếp từ. Tòa nhà có thang máy, khóa thẻ từ, camera. Phù hợp sinh viên, người đi làm trẻ.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Thang máy', 'Bảo vệ', 'Nấu ăn'],
    contact: { name: 'Hoàng Minh Quân', phone: '0923456789' },
    showPhone: true,
    latitude: 10.8069,
    longitude: 106.6795,
    status: 'active',
    createdAt: daysAgo(3),
    rating: 4.6,
    reviewCount: 11,
    condition: 'new',
    views: 4_800,
    contactCount: 36,
    savedCount: 74,
  },
  {
    id: 'bds026',
    title: 'Nhà nguyên căn 3 tầng Tân Bình — hẻm xe hơi, 4PN',
    price: 25_000_000,
    area: 110,
    districtId: 'tanbinh',
    district: 'Tân Bình',
    ward: 'Phường 13',
    address: '26 Cộng Hòa, Tân Bình',
    type: 'nha_nguyen_can',
    deal: 'rent',
    bedrooms: 4,
    bathrooms: 3,
    floor: 3,
    yearBuilt: 2019,
    description:
      'Nhà nguyên căn 3 tầng 110m², hẻm xe hơi, 4 phòng ngủ, 3 wc. Nội thất cơ bản sạch sẽ, sân thượng rộng phơi đồ. Gần sân bay, chợ, thích hợp gia đình hoặc ở ghép nhóm đông người.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Bếp riêng', 'Ban công'],
    contact: { name: 'Trần Quốc Thắng', phone: '0934567890' },
    showPhone: true,
    latitude: 10.7997,
    longitude: 106.6567,
    status: 'active',
    createdAt: daysAgo(4),
    condition: 'new',
    views: 7_100,
    contactCount: 53,
    savedCount: 121,
  },
  {
    id: 'bds027',
    title: 'Phòng trọ gần ĐH KHTN — 3.1 triệu, wc riêng, sạch',
    price: 3_100_000,
    area: 19,
    districtId: 'q10',
    district: 'Quận 10',
    ward: 'Phường 12',
    address: '35 Ngô Gia Tự, Quận 10',
    type: 'phong_tro',
    deal: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    floor: 1,
    yearBuilt: 2020,
    description:
      'Phòng 19m² tầng trệt, wc riêng, cửa sổ thoáng. Máy lạnh, giường tủ, bàn học. Cách ĐH Khoa học Tự nhiên 500m. Khu ăn uống đông đúc, an ninh tốt, chủ nhà thân thiện.',
    amenities: ['WiFi', 'Máy lạnh', 'WC riêng'],
    contact: { name: 'Nguyễn Thị Ngà', phone: '0945678901' },
    showPhone: true,
    latitude: 10.7592,
    longitude: 106.6825,
    status: 'active',
    createdAt: daysAgo(5),
    rating: 4.3,
    reviewCount: 7,
    condition: 'needs_repair',
    views: 3_500,
    contactCount: 22,
    savedCount: 51,
  },
  {
    id: 'bds028',
    title: 'Căn hộ 1PN Thủ Đức view mặt trời — gần ga metro số 1',
    price: 8_200_000,
    area: 55,
    districtId: 'thuduc',
    district: 'Thủ Đức',
    ward: 'Phường Linh Trung',
    address: '1 Song Hành, Thủ Đức',
    type: 'can_ho',
    deal: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    floor: 8,
    yearBuilt: 2021,
    description:
      'Căn hộ 1 phòng ngủ 55m² view hướng Đông đón nắng sáng. Ban công rộng, bếp liền khách, nội thất đầy đủ. Gần ga Metro số 1, Siêu thị, trường học. Hồ bơi + gym của chung cư.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Máy giặt', 'Thang máy', 'Bảo vệ', 'Ban công'],
    contact: { name: 'Lê Khánh Hà', phone: '0956789012' },
    showPhone: true,
    latitude: 10.8431,
    longitude: 106.7666,
    status: 'active',
    createdAt: daysAgo(6),
    rating: 4.7,
    reviewCount: 12,
    condition: 'new',
    direction: 'Đông',
    views: 9_900,
    contactCount: 68,
    savedCount: 164,
  },
  {
    id: 'bds029',
    title: 'Phòng trọ có gác lửng Bình Thạnh — giá 2.9 triệu',
    price: 2_900_000,
    area: 18,
    districtId: 'binhthanh',
    district: 'Bình Thạnh',
    ward: 'Phường 25',
    address: '68 Ngô Tất Tố, Bình Thạnh',
    type: 'phong_tro',
    deal: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    floor: 2,
    yearBuilt: 2019,
    description:
      'Phòng 18m² có gác lửng để đồ, tầng 2 không ồn. Máy lạnh, wc riêng, khu nấu ăn riêng. Gần ĐH Kinh tế, chợ Bình Thạnh. Đường Ngô Tất Tố nhiều quán ăn ngon, sinh viên đông.',
    amenities: ['WiFi', 'Máy lạnh', 'WC riêng', 'Nấu ăn'],
    contact: { name: 'Phạm Thị Hoa', phone: '0967890123' },
    showPhone: true,
    latitude: 10.8055,
    longitude: 106.7002,
    status: 'active',
    createdAt: daysAgo(7),
    rating: 4.4,
    reviewCount: 6,
    condition: 'new',
    views: 2_800,
    contactCount: 17,
    savedCount: 44,
  },
  {
    id: 'bds030',
    title: 'Căn hộ mini Gò Vấp 1PN + 1 gác — nội thất mới',
    price: 4_500_000,
    area: 32,
    districtId: 'govap',
    district: 'Gò Vấp',
    ward: 'Phường 3',
    address: '88 Quang Trung, Gò Vấp',
    type: 'can_ho',
    deal: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    floor: 3,
    yearBuilt: 2022,
    description:
      'Căn hộ mini 32m² gác lửng ngủ, dưới để bếp khách. Nội thất mới 100%, máy lạnh, tủ lạnh, máy giặt. Tòa nhà mới có thang máy, khóa vân tay. Gần chợ, bệnh viện Gò Vấp.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Máy giặt', 'Thang máy', 'Bảo vệ'],
    contact: { name: 'Vũ Quốc Bảo', phone: '0978901234' },
    showPhone: true,
    latitude: 10.8321,
    longitude: 106.6712,
    status: 'active',
    createdAt: daysAgo(8),
    rating: 4.6,
    reviewCount: 9,
    condition: 'new',
    views: 5_200,
    contactCount: 39,
    savedCount: 88,
  },
  {
    id: 'bds031',
    title: 'Căn hộ 2PN Quận 3 — nội thất cũ nhưng rộng, giá tốt',
    price: 12_500_000,
    area: 78,
    districtId: 'q3',
    district: 'Quận 3',
    ward: 'Phường 1',
    address: '145 Cách Mạng Tháng 8, Quận 3',
    type: 'can_ho',
    deal: 'rent',
    bedrooms: 2,
    bathrooms: 2,
    floor: 5,
    yearBuilt: 2015,
    description:
      'Căn hộ 78m² rộng rãi, phòng khách lớn, 2 phòng ngủ. Nội thất cũ nhưng còn sử dụng tốt, thích hợp ai thích diện tích thoáng và ở lâu dài. Gần trung tâm, chợ, ngân hàng.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Thang máy', 'Bảo vệ'],
    contact: { name: 'Đinh Thị Mai', phone: '0989012345' },
    showPhone: true,
    latitude: 10.7719,
    longitude: 106.6866,
    status: 'active',
    createdAt: daysAgo(9),
    rating: 4.2,
    reviewCount: 5,
    condition: 'needs_repair',
    views: 4_600,
    contactCount: 31,
    savedCount: 67,
  },
  {
    id: 'bds032',
    title: 'Phòng trọ có cửa sổ trời Quận 10 — 2.6 triệu, WC riêng',
    price: 2_600_000,
    area: 17,
    districtId: 'q10',
    district: 'Quận 10',
    ward: 'Phường 15',
    address: '210 Thành Thái, Quận 10',
    type: 'phong_tro',
    deal: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    floor: 4,
    yearBuilt: 2020,
    description:
      'Phòng 17m² tầng 4 có cửa sổ trời đón sáng thiên nhiên. Máy lạnh, giường tủ, wc riêng. Cách ĐH Kinh tế, ĐH Y Dược gần. Khu yên tĩnh, chủ nhà tốt, giá phải chăng.',
    amenities: ['WiFi', 'Máy lạnh', 'WC riêng', 'Nấu ăn'],
    contact: { name: 'Cao Mỹ Linh', phone: '0990123456' },
    showPhone: true,
    latitude: 10.7635,
    longitude: 106.6713,
    status: 'active',
    createdAt: daysAgo(10),
    rating: 4.1,
    reviewCount: 4,
    condition: 'needs_repair',
    views: 2_100,
    contactCount: 14,
    savedCount: 33,
  },

  // ---------- BÁN (deal: 'sale') ----------
  {
    id: 'bds033',
    title: 'Căn hộ 2PN view sông Quận 7 — bàn giao nội thất cao cấp',
    price: 3_100_000_000,
    area: 75,
    districtId: 'q7',
    district: 'Quận 7',
    ward: 'Phường Phú Mỹ',
    address: '18 Nguyễn Lương Bằng, Quận 7',
    type: 'can_ho',
    deal: 'sale',
    bedrooms: 2,
    bathrooms: 2,
    floor: 15,
    yearBuilt: 2022,
    direction: 'Đông Nam',
    legal: 'Sổ hồng',
    frontage: 5,
    furnished: 'full',
    description:
      'Căn hộ 2PN 75m² view sông, chung cư cao cấp hồ bơi resort. Bàn giao nội thất full, sổ hồng sở hữu lâu dài. Gần Phú Mỹ Hưng, Lotte Mart. Giá hợp lý, có hỗ trợ vay ngân hàng.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Máy giặt', 'TV', 'Thang máy', 'Bảo vệ', 'Ban công'],
    contact: { name: 'Nguyễn Văn Nam', phone: '0901112233', email: 'nam.bds@gmail.com' },
    showPhone: true,
    latitude: 10.7386,
    longitude: 106.7083,
    status: 'active',
    createdAt: daysAgo(3),
    rating: 4.8,
    reviewCount: 10,
    condition: 'new',
    views: 15_400,
    contactCount: 92,
    savedCount: 210,
  },
  {
    id: 'bds034',
    title: 'Đất nền ven sông Bình Thạnh — sổ đỏ, giá đầu tư tốt',
    price: 5_500_000_000,
    area: 120,
    districtId: 'binhthanh',
    district: 'Bình Thạnh',
    ward: 'Phường 26',
    address: 'khu ven sông Thanh Đa, Bình Thạnh',
    type: 'dat_nen',
    deal: 'sale',
    bedrooms: 0,
    bathrooms: 0,
    direction: 'Nam',
    legal: 'Sổ đỏ',
    frontage: 6,
    description:
      'Đất nền 120m² khu ven sông Thanh Đa, hạ tầng mới, đường rộng, khí hậu mát. Xây được 3 tầng, gần công viên, cảng. Sổ đỏ chính chủ, pháp lý rõ ràng, thích hợp đầu tư hoặc xây biệt thự.',
    amenities: ['Bảo vệ'],
    contact: { name: 'Trần Thị Hạnh', phone: '0902223344' },
    showPhone: true,
    latitude: 10.8156,
    longitude: 106.7091,
    status: 'active',
    createdAt: daysAgo(4),
    rating: 4.5,
    reviewCount: 3,
    condition: 'new',
    views: 6_800,
    contactCount: 47,
    savedCount: 118,
  },
  {
    id: 'bds035',
    title: 'Nhà mặt tiền Quận 1 — kinh doanh đắc địa, 1 trệt 3 lầu',
    price: 38_000_000_000,
    area: 90,
    districtId: 'q1',
    district: 'Quận 1',
    ward: 'Phường Đa Kao',
    address: '250 Điện Biên Phủ, Quận 1',
    type: 'nha_nguyen_can',
    deal: 'sale',
    bedrooms: 4,
    bathrooms: 5,
    floor: 3,
    yearBuilt: 2018,
    direction: 'Đông',
    legal: 'Sổ hồng',
    frontage: 6,
    furnished: 'full',
    description:
      'Nhà mặt tiền kinh doanh 90m², 1 trệt 3 lầu, 4 phòng ngủ. Vị trí vàng ngay Điện Biên Phủ, khu Đa Kao nhiều nhà hàng. Thu nhập cho thuê ổn định, sổ hồng hoàn công đầy đủ.',
    amenities: ['Máy lạnh', 'Tủ lạnh', 'Bảo vệ', 'Thang máy'],
    contact: { name: 'Lê Minh Châu', phone: '0903334455', email: 'chau.le@gmail.com' },
    showPhone: false,
    latitude: 10.7875,
    longitude: 106.6849,
    status: 'active',
    createdAt: daysAgo(5),
    rating: 4.9,
    reviewCount: 6,
    condition: 'new',
    views: 22_300,
    contactCount: 133,
    savedCount: 289,
  },
  {
    id: 'bds036',
    title: 'Căn hộ 1PN nội thất Quận 5 — nằm gần chợ Hàn Quốc',
    price: 2_400_000_000,
    area: 50,
    districtId: 'q5',
    district: 'Quận 5',
    ward: 'Phường 14',
    address: '55 An Dương Vương, Quận 5',
    type: 'can_ho',
    deal: 'sale',
    bedrooms: 1,
    bathrooms: 1,
    floor: 10,
    yearBuilt: 2019,
    direction: 'Tây',
    legal: 'Sổ hồng',
    frontage: 4,
    furnished: 'basic',
    description:
      'Căn hộ 1PN 50m² nội thất cơ bản, hợp đầu tư cho thuê (khu chợ Hàn Quốc đông khách nước ngoài). Gần bệnh viện Chợ Rẫy, trường học. Sổ hồng, sang nhượng nhanh.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Thang máy', 'Bảo vệ'],
    contact: { name: 'Võ Thanh Sang', phone: '0904445566' },
    showPhone: true,
    latitude: 10.7572,
    longitude: 106.6701,
    status: 'active',
    createdAt: daysAgo(6),
    rating: 4.6,
    reviewCount: 4,
    condition: 'new',
    views: 9_100,
    contactCount: 63,
    savedCount: 142,
  },
  {
    id: 'bds037',
    title: 'Đất nền khu dân cư Tân Bình — sổ hồng, xây tự do',
    price: 6_800_000_000,
    area: 150,
    districtId: 'tanbinh',
    district: 'Tân Bình',
    ward: 'Phường 2',
    address: 'khu dân cư Tây Thạnh, Tân Bình',
    type: 'dat_nen',
    deal: 'sale',
    bedrooms: 0,
    bathrooms: 0,
    direction: 'Bắc',
    legal: 'Sổ hồng',
    frontage: 7,
    description:
      'Đất nền 150m² khu dân cư yên tĩnh Tây Thạnh, đường ô tô 8m. Xây được biệt thự vườn, gần công viên, siêu thị. Sổ hồng riêng từng nền, pháp lý chuẩn, hỗ trợ giấy phép xây dựng.',
    amenities: ['Bảo vệ'],
    contact: { name: 'Phạm Đức Anh', phone: '0905556677' },
    showPhone: true,
    latitude: 10.8132,
    longitude: 106.6357,
    status: 'active',
    createdAt: daysAgo(7),
    rating: 4.4,
    reviewCount: 2,
    condition: 'new',
    views: 3_900,
    contactCount: 28,
    savedCount: 61,
  },
  {
    id: 'bds038',
    title: 'Nhà phố 2 tầng Thủ Đức — sổ hồng, hẻm xe hơi',
    price: 8_500_000_000,
    area: 90,
    districtId: 'thuduc',
    district: 'Thủ Đức',
    ward: 'Phường Hiệp Bình Chánh',
    address: '30 Quốc Lộ 13, Thủ Đức',
    type: 'nha_nguyen_can',
    deal: 'sale',
    bedrooms: 3,
    bathrooms: 3,
    floor: 2,
    yearBuilt: 2020,
    direction: 'Đông Nam',
    legal: 'Sổ hồng',
    frontage: 5,
    furnished: 'full',
    description:
      'Nhà phố 2 tầng 90m² mới xây, hẻm xe hơi, 3 phòng ngủ. Nội thất khá đầy đủ, sân trước rộng. Gần chợ, trường học, giao thông thuận tiện về trung tâm. Sổ hồng hoàn công 2020.',
    amenities: ['Máy lạnh', 'Tủ lạnh', 'Bếp riêng', 'Ban công'],
    contact: { name: 'Lý Mỹ Duyên', phone: '0906667788' },
    showPhone: true,
    latitude: 10.8330,
    longitude: 106.7190,
    status: 'active',
    createdAt: daysAgo(8),
    rating: 4.7,
    reviewCount: 5,
    condition: 'new',
    views: 12_000,
    contactCount: 84,
    savedCount: 196,
  },
  {
    id: 'bds039',
    title: 'Căn hộ 3PN hạng sang Quận 7 — penthouse view sông',
    price: 12_000_000_000,
    area: 200,
    districtId: 'q7',
    district: 'Quận 7',
    ward: 'Phường Tân Thuận Đông',
    address: '250 Nguyễn Văn Linh, Quận 7',
    type: 'can_ho',
    deal: 'sale',
    bedrooms: 3,
    bathrooms: 5,
    floor: 30,
    yearBuilt: 2022,
    direction: 'Tây Nam',
    legal: 'Sổ hồng',
    frontage: 8,
    furnished: 'full',
    description:
      'Penthouse 200m² hạng sang view sông Hàn Quốc. Trần cao 4m, cửa kính panorama, nội thất chuẩn resort. Hồ bơi tầng thượng, sảnh riêng. Phù hợp gia đình đẳng cấp hoặc đầu tư lâu dài.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Máy giặt', 'TV', 'Thang máy', 'Bảo vệ', 'Ban công'],
    contact: { name: 'Hoàng Gia Khang', phone: '0907778899', email: 'khang.hoang@luxe.vn' },
    showPhone: false,
    latitude: 10.7333,
    longitude: 106.7001,
    status: 'active',
    createdAt: daysAgo(2),
    rating: 5.0,
    reviewCount: 8,
    condition: 'new',
    views: 19_700,
    contactCount: 116,
    savedCount: 278,
  },
  {
    id: 'bds040',
    title: 'Nhà phố Gò Vấp 3 tầng — mới đẹp, hẻm xe hơi',
    price: 7_800_000_000,
    area: 100,
    districtId: 'govap',
    district: 'Gò Vấp',
    ward: 'Phường 10',
    address: '120 Nguyễn Oanh, Gò Vấp',
    type: 'nha_nguyen_can',
    deal: 'sale',
    bedrooms: 3,
    bathrooms: 4,
    floor: 3,
    yearBuilt: 2021,
    direction: 'Nam',
    legal: 'Sổ hồng',
    frontage: 5,
    furnished: 'full',
    description:
      'Nhà phố 3 tầng 100m² mới xây 2021, hẻm xe hơi vào tận nơi. Nội thất đầy đủ, sân thượng thoáng, có phòng thờ. Gần chợ Nguyễn Oanh, trường học. Sổ hồng hoàn công, mua bán nhanh.',
    amenities: ['Máy lạnh', 'Tủ lạnh', 'Bếp riêng', 'Thang máy', 'Ban công'],
    contact: { name: 'Trịnh Văn Phúc', phone: '0908889900' },
    showPhone: true,
    latitude: 10.8291,
    longitude: 106.6887,
    status: 'active',
    createdAt: daysAgo(1),
    rating: 4.8,
    reviewCount: 4,
    condition: 'new',
    views: 10_500,
    contactCount: 72,
    savedCount: 165,
  },
  {
    id: 'bds041',
    title: 'Đất biệt thự 200m² Quận 9 — view sông, sổ đỏ',
    price: 9_200_000_000,
    area: 200,
    districtId: 'thuduc',
    district: 'Thủ Đức',
    ward: 'Phường Hiệp Bình Chánh',
    address: 'khu biệt thự Long Phước, Thủ Đức',
    type: 'dat_nen',
    deal: 'sale',
    bedrooms: 0,
    bathrooms: 0,
    direction: 'Đông Nam',
    legal: 'Sổ đỏ',
    frontage: 10,
    description:
      'Đất biệt thự 200m² ven sông Đồng Nai, view mát mẻ. Hạ tầng hoàn chỉnh, đường 12m, cây xanh. Xây được biệt thự 2 tầng, gần khu du lịch. Sổ đỏ chính chủ, giá tốt cho phân khúc biệt thự.',
    amenities: ['Bảo vệ'],
    contact: { name: 'Đỗ Xuân Hải', phone: '0909990011' },
    showPhone: true,
    latitude: 10.8485,
    longitude: 106.7742,
    status: 'active',
    createdAt: daysAgo(3),
    rating: 4.3,
    reviewCount: 3,
    condition: 'new',
    views: 5_600,
    contactCount: 38,
    savedCount: 85,
  },
  {
    id: 'bds042',
    title: 'Căn hộ 2PN Quận 1 khu Thủ Thiêm — view Landmark, sổ hồng',
    price: 4_500_000_000,
    area: 88,
    districtId: 'q1',
    district: 'Quận 1',
    ward: 'Phường Bến Nghé',
    address: 'phường Bến Nghé, Quận 1',
    type: 'can_ho',
    deal: 'sale',
    bedrooms: 2,
    bathrooms: 2,
    floor: 20,
    yearBuilt: 2021,
    direction: 'Đông Nam',
    legal: 'Sổ hồng',
    frontage: 6,
    furnished: 'full',
    description:
      'Căn hộ 2PN 88m² view Landmark 81, chung cư hạng sang. Nội thất full cao cấp, hồ bơi, gym, sảnh đón khách 5 sao. Sổ hồng sở hữu vĩnh viễn, có thể cho thuê giá tốt.',
    amenities: ['WiFi', 'Máy lạnh', 'Tủ lạnh', 'Máy giặt', 'TV', 'Thang máy', 'Bảo vệ', 'Ban công'],
    contact: { name: 'Phan Thu Hà', phone: '0910001122' },
    showPhone: true,
    latitude: 10.7107,
    longitude: 106.7209,
    status: 'active',
    createdAt: daysAgo(5),
    rating: 4.9,
    reviewCount: 7,
    condition: 'new',
    views: 17_000,
    contactCount: 105,
    savedCount: 241,
  },
];

async function main(): Promise<void> {
  console.log(`\nSeed +${MORE.length} tin mới (bds023–bds042) → project: ${process.env.GCLOUD_PROJECT ?? '(theo key)'}\n`);

  const batch = db.batch();
  let added = 0;
  for (const m of MORE) {
    const { id, ...data } = m;
    const docData = {
      ...data,
      images: nextImages(),
      ownerUid: '',
      isFavorite: false,
    };
    if (!docData.views) delete docData.views;
    if (!docData.rating) delete docData.rating;
    if (!docData.deal) delete docData.deal;
    batch.set(db.collection('listings').doc(id), docData);
    added++;
  }
  await batch.commit();
  console.log(`✓ listings: ghi ${added} tin mới (bds023–bds042)`);

  // Cập nhật lại các tin cũ bds001–bds022 để bổ sung field `deal`
  // (bds021 là đất bán, bds022 là nhà bán → 'sale'; còn lại cho thuê → 'rent')
  const MIN_ID = 'bds001';
  const MAX_ID_NEW = 'bds042';
  const saleIds = ['bds021', 'bds022'];
  const updated = db.batch();
  const snap = await db.collection('listings').where('id', '>=', MIN_ID).where('id', '<=', MAX_ID_NEW).get();
  let backfilled = 0;
  snap.forEach((doc) => {
    const data = doc.data() as { deal?: string };
    if (data.deal) return;
    updated.update(doc.ref, { deal: saleIds.includes(doc.id) ? 'sale' : 'rent' });
    backfilled++;
  });
  if (backfilled) {
    await updated.commit();
    console.log(`✓ listings: bổ sung field deal cho ${backfilled} tin cũ (bds001–bds022 → rent/sale)`);
  } else {
    console.log('✓ Không cần bổ sung deal cho tin cũ (đã có sẵn)');
  }

  const total = await db.collection('listings').count().get();
  console.log(`✓ Tổng số tin hiện có trên Firestore: ${total.data().count}\n`);
}

main()
  .catch((err) => {
    console.error('\n[!] Seed lỗi:', err);
    process.exit(1);
  })
  .then(() => process.exit(0));
